CREATE TABLE IF NOT EXISTS City (
	id MEDIUMINT UNSIGNED PRIMARY KEY,
	geonameid INT UNSIGNED UNIQUE NOT NULL,
	name CHAR(100) NOT NULL COLLATE utf8_bin,
	asciiname CHAR(100) COLLATE utf8_bin,
	altnames CHAR(200) COLLATE utf8_bin,
	latitude FLOAT NOT NULL,
	longitude FLOAT NOT NULL,
	feat_class CHAR(1) NOT NULL COLLATE utf8_bin,
	feat_code CHAR(5) NOT NULL COLLATE utf8_bin,
	country_code CHAR(2) COLLATE utf8_bin,
	cc2 CHAR(5) COLLATE utf8_bin,
	admin1_code CHAR(10) COLLATE utf8_bin,
	admin2_code CHAR(50) COLLATE utf8_bin,
	admin3_code CHAR(10) COLLATE utf8_bin,
	admin4_code CHAR(20) COLLATE utf8_bin,
	population INT UNSIGNED NOT NULL,
	elevation FLOAT,
	dem SMALLINT NOT NULL,
	timezone CHAR(32) COLLATE utf8_bin,
	modified DATE,
	INDEX (name),
	INDEX (latitude, longitude),
	INDEX (feat_class),
	INDEX (feat_code),
	INDEX (cc2),
	INDEX (country_code),
	INDEX (admin1_code),
	INDEX (admin2_code),
	INDEX (admin3_code),
	INDEX (admin4_code),
	INDEX (population),
	INDEX (elevation),
	INDEX (timezone),
	INDEX (modified)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
